name: "Terraform Deployment"

on:
  push:
    branches:
      - users/shubhi/terraform  # Use the correct branch name
  pull_request:
    branches:
      - users/shubhi/terraform

permissions:
  contents: read
  id-token: write


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Use the latest stable version

      - name: Azure Login
        uses: azure/login@v1
        env:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform  
        

      - name: Terraform Plan
        run: terraform plan 
        working-directory: terraform
        

